design/CM/Color_Manager.v
design/CM/Color_Manager_Assign_Data.v
design/CM/Color_Manager_Config_Manager.v
design/CM/Color_Manager_Counter.v
design/CS/CS.v
design/DB/DB.v
design/DB/DB_debouncer.v
design/LM/LM.v
design/LM/LM_decoder.v
design/FIFO/Sync_Reg.v
design/UART/UART.v
design/UART/UART_config.v
design/UART/UART_sampler.v
design/UART/UART_state.v
design/VGA/VGA_Assign_color.v
design/VGA/VGA_Config.v
design/VGA/VGA_Control.v
design/VGA/VGA_Counter.v
design/CD/CD.v
design/CD/CD_config.v
design/CD/CD_counter.v

design/TB/Color_Manager_tb.v
design/TB/tb_CD.v
design/TB/tb_CS.v
design/TB/tb_DB.v
design/TB/tb_LM.v
design/TB/tb_Sync_Reg.v
design/TB/tb_UART.v
design/TB/VGA_Control_tb.v
